config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'

  resources :posts
  resources :comments
  
  devise_for :users

  root 'posts#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, :all
    can :create, Comment    
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_nested_set :scope => [:commentable_id, :commentable_type]

  validates :body, :presence => true
  validates :user, :presence => true

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_votable

  belongs_to :commentable, :polymorphic => true

  # NOTE: Comments belong to a user
  belongs_to :user

  # Helper class method that allows you to build a comment
  # by passing a commentable object, a user_id, and comment text
  # example in readme
  def self.build_from(obj, user_id, comment)
    new \
      :commentable => obj,
      :body        => comment,
      :user_id     => user_id
  end

  #helper method to check if a comment has children
  def has_children?
    self.children.any?
  end

  # Helper class method to lookup all comments assigned
  # to all commentable types for a given user.
  scope :find_comments_by_user, lambda { |user|
    where(:user_id => user.id).order('created_at DESC')
  }

  # Helper class method to look up all comments for
  # commentable class name and commentable id.
  scope :find_comments_for_commentable, lambda { |commentable_str, commentable_id|
    where(:commentable_type => commentable_str.to_s, :commentable_id => commentable_id).order('created_at DESC')
  }

  # Helper class method to look up a commentable object
  # given the commentable class name and id
  def self.find_commentable(commentable_str, commentable_id)
    commentable_str.constantize.find(commentable_id)
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	acts_as_commentable

	def get_comments
      self.root_comments.includes(:user).includes(:children).order("created_at DESC")
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  require 'coderay'
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:edit, :update, :destroy]
  load_and_authorize_resource
  
  
  def new
    @child_comment = Comment.new(
      parent_id: params[:parent_id], 
      commentable_id: params[:post_id])
    respond_to do |format|
      format.html { render :partial => 'comments/new', 
        :object => @child_comment, :as => 'comment' }
    end
  end

  def create
    post = Post.find(params[:comment][:commentable_id])
    @comment = Comment.build_from(post, current_user.id, params[:comment][:body])
    respond_to do |format|
      if @comment.save
        if is_children?
          format.html { render :partial => "comments/child_comment",
            locals: { comment: @comment }, :status => :created }
        else
          format.html { render :partial => "comments/comment", 
            locals: { comment: @comment, post_id: @comment.commentable_id }, 
            :status => :created }
        end
      else
        format.html { redirect_to :back, norice: 'Something went wrong.' }
        format.json { render json: comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    render partial: 'comments/new', :object => @comment, :as => 'comment'
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.json { render json: @comment }
      else
        format.html { redirect_to :back }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end 

  def destroy
    respond_to do |format|
      if @comment.destroy
         format.json { render json: @comment }
      else
        format.html { redirect_to :back, notice: 'Post was successfully destroyed.' }
      end
    end
  end

  private

    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:id, :body, :commentable_id, :parent_id)
    end

    def is_children?
      parent_id = params[:comment][:parent_id]
      unless parent_id.empty?
        parent_comment = Comment.find(parent_id)
        @comment.move_to_child_of(parent_comment)
        true
      else
        false
      end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource
  


  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new(:commentable_id => @post.id)    
    @comments = @post.get_comments    
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_name(user)
    unless user.nil?
      user.email
    else
      "Unknown"
    end
  end

  def scancode(text)
    CodeRay.scan( text, :ruby, :html).div.html_safe
  end

  class MarkdownRenderer < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.highlight(code, language)
    end
  end
  
  def markdown(text)
    rndr = MarkdownRenderer.new(:filter_html => true, :hard_wrap => true)
    options = {
      :fenced_code_blocks => true,
      :no_intra_emphasis => true,
      :autolink => true,
      :strikethrough => true,
      :lax_html_blocks => true,
      :superscript => true,
      :highlight => true
    }
    markdown_to_html = Redcarpet::Markdown.new(rndr, options)
    markdown_to_html
    #.render(text).html_safe
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_child_comment.html.erb
<div id="comment_<%= comment.id %>">
<table class="table" >
  <tr>
    <td><%= full_name(comment.user) %></td>
    <td><small class="pull-right">
      <%= comment.created_at.strftime("%d %B %Y at %H:%M") %>
      <% if can? :destroy, Comment %>
      <%= link_to 'Delete', comment_path(comment), remote: true, data: { method: :delete }, :class => "delete_comment" %> 
      <%= link_to "Edit", edit_comment_path(comment), remote: true, :class => "edit_comment_url" %>
      <% end %>
    </small></td>
  </tr>
  <tr>
    <td colspan="2">
      <span class="comment_body"><%= scancode comment.body %></span>
    </td>
  </tr>  
</table>
</div>


app/views/comments/_comment.html.erb
<div class="panel panel-default comments_panel" id="comment_<%= comment.id %>">
  <div class="panel-heading">
    <%= full_name(comment.user) %>
    <br />
    <%= comment.created_at.strftime("%d %B %Y at %H:%M") %>
    <div class="pull-right">
      <% if can? :destroy, Comment %>
        <%= link_to 'Delete', comment_path(comment), remote: true, data: { method: :delete }, :class => "delete_comment" %> 
        <%= link_to "Edit", edit_comment_path(comment), remote: true, :class => "edit_comment_url" %>
      <% end %>
    </div>
  </div>
  <div class="panel-body">
      <div class="row">        
        <div class="col-md-10">
          <span class="comment_body"><%= scancode comment.body %></span>
        </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="pull-right">
          <% if can? :create, Comment %>
            <div class="row">
              <div class="col-md-6">
                <%= link_to "Reply", new_comment_path(post_id: post_id, parent_id: comment.id), remote: true, class: "btn btn-default reply" %>
              </div>
              <div class="col-md-6">
                <%= link_to "Quote", new_comment_path(post_id: post_id, parent_id: comment.id), remote: true, class: "btn btn-default" %>
              </div><br><br>
          <% end %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 children">
        <%= render partial: 'comments/child_comment', collection: comment.children, as: :comment %>
      </div>
    </div>
</div>
</div>
</div>

app/views/comments/_new.html.erb
<div class="panel panel-default new_comment_panel">
  <div class="panel-heading">
    <%= full_name(current_user) %>
  </div>
  <div class="panel-body">
    <div class="row">
    <div class="col-md-12">
      <%= form_for(comment, remote: true) do |c| %>
        <%= c.text_area :body, :class => "form-control"  %>
        <%= c.hidden_field :commentable_id, value: comment.commentable_id %>
        <%= c.hidden_field :parent_id, value: comment.parent_id %><br>
        <%= c.submit :class => "btn btn-default" %>
      <% end %>
    </div>
  </div>
  </div>
</div>

app/views/comments/create.html.erb
<h1>Comments#create</h1>

app/views/comments/new.html.erb
<%= @child_comment.parent_id  %>
<%= @child_comment.commentable_id %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coms</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="jumbotron" style="padding: 20px;">
    <div class="panel panel-default" style="padding: 20px;">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.user_id %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= scancode @post.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

<h2>Comments (<%= @post.comment_threads.count %>) </h2>

<hr>
  <%= render partial: 'comments/new', object: @comment, as: 'comment' if can? :create, Comment %><hr>
  <div id="comments"><%= render partial: 'comments/comment', collection: @comments, as: :comment, locals: { post_id: @post.id} %></div>